name: "Word of the Day"
description: "Word of the Day add-on for Home Assistant by Morgan Currie"
version: "1.0.0"
slug: "word_of_the_day_mc"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services

homeassistant_api: true
