# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Word of the Day"
description: "Word of the Day add-on for Home Assistant by Morgan Currie"
version: "1.0.1"
slug: "word_of_the_day_mc"
url: "https://github.com/morgancurrie/word_of_the_day_ha_addon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
startup: services

homeassistant_api: true
